create table Client_Data (
	client_id VARCHAR(50),
	company_name VARCHAR(50)
);
insert into Client_Data (client_id, company_name) values (400000, 'Mueller, Stamm and Gislason');
insert into Client_Data (client_id, company_name) values (400001, 'Schuppe-Miller');
insert into Client_Data (client_id, company_name) values (400002, 'Bechtelar Inc');
insert into Client_Data (client_id, company_name) values (400003, 'Batz Group');
insert into Client_Data (client_id, company_name) values (400004, 'Davis and Sons');
insert into Client_Data (client_id, company_name) values (400005, 'Padberg-Hoppe');
insert into Client_Data (client_id, company_name) values (400006, 'Quigley, Pollich and Kuvalis');
insert into Client_Data (client_id, company_name) values (400007, 'Yundt, Bosco and Volkman');
insert into Client_Data (client_id, company_name) values (400008, 'Frami, Hauck and Purdy');
insert into Client_Data (client_id, company_name) values (400009, 'Smitham-Zieme');
insert into Client_Data (client_id, company_name) values (400010, 'Sanford, Schmidt and Donnelly');
insert into Client_Data (client_id, company_name) values (400011, 'Koelpin Inc');
insert into Client_Data (client_id, company_name) values (400012, 'Hackett, Ledner and Kub');
insert into Client_Data (client_id, company_name) values (400013, 'Gorczany-O''Connell');
insert into Client_Data (client_id, company_name) values (400014, 'Tillman, Cremin and Bogisich');
insert into Client_Data (client_id, company_name) values (400015, 'Bode, Waelchi and Schuster');
insert into Client_Data (client_id, company_name) values (400016, 'Hudson LLC');
insert into Client_Data (client_id, company_name) values (400017, 'Beer-Monahan');
insert into Client_Data (client_id, company_name) values (400018, 'Jakubowski, Deckow and Ward');
insert into Client_Data (client_id, company_name) values (400019, 'Bogan and Sons');
insert into Client_Data (client_id, company_name) values (400020, 'Predovic LLC');
insert into Client_Data (client_id, company_name) values (400021, 'Fahey-King');
insert into Client_Data (client_id, company_name) values (400022, 'Considine Group');
insert into Client_Data (client_id, company_name) values (400023, 'Jerde-White');
insert into Client_Data (client_id, company_name) values (400024, 'Spencer, Dibbert and Marks');
insert into Client_Data (client_id, company_name) values (400025, 'Wolf Group');
insert into Client_Data (client_id, company_name) values (400026, 'Fritsch Inc');
insert into Client_Data (client_id, company_name) values (400027, 'Kohler-Schmitt');
insert into Client_Data (client_id, company_name) values (400028, 'Predovic, Wilderman and Stark');
insert into Client_Data (client_id, company_name) values (400029, 'Murazik Inc');
insert into Client_Data (client_id, company_name) values (400030, 'Hagenes-Gutkowski');
insert into Client_Data (client_id, company_name) values (400031, 'Roberts-Turner');
insert into Client_Data (client_id, company_name) values (400032, 'Predovic-Reinger');
insert into Client_Data (client_id, company_name) values (400033, 'McGlynn LLC');
insert into Client_Data (client_id, company_name) values (400034, 'Lang-Leuschke');
insert into Client_Data (client_id, company_name) values (400035, 'Lang-Schaden');
insert into Client_Data (client_id, company_name) values (400036, 'Runolfsdottir-Keeling');
insert into Client_Data (client_id, company_name) values (400037, 'Pollich-Kihn');
insert into Client_Data (client_id, company_name) values (400038, 'Jacobson LLC');
insert into Client_Data (client_id, company_name) values (400039, 'Renner Inc');
insert into Client_Data (client_id, company_name) values (400040, 'Mayert-Dietrich');
insert into Client_Data (client_id, company_name) values (400041, 'Krajcik, Kemmer and Durgan');
insert into Client_Data (client_id, company_name) values (400042, 'Borer, Hartmann and Littel');
insert into Client_Data (client_id, company_name) values (400043, 'Parker, Kunze and MacGyver');
insert into Client_Data (client_id, company_name) values (400044, 'Nienow-McClure');
insert into Client_Data (client_id, company_name) values (400045, 'Koepp-McDermott');
insert into Client_Data (client_id, company_name) values (400046, 'Jakubowski LLC');
insert into Client_Data (client_id, company_name) values (400047, 'Ratke-Stark');
insert into Client_Data (client_id, company_name) values (400048, 'Marvin and Sons');
insert into Client_Data (client_id, company_name) values (400049, 'Bernhard LLC');
insert into Client_Data (client_id, company_name) values (400050, 'Russel, Stanton and Lang');
insert into Client_Data (client_id, company_name) values (400051, 'Conroy, Armstrong and Howe');
insert into Client_Data (client_id, company_name) values (400052, 'Murphy, Blanda and Baumbach');
insert into Client_Data (client_id, company_name) values (400053, 'Rodriguez, Gislason and Kub');
insert into Client_Data (client_id, company_name) values (400054, 'Padberg-White');
insert into Client_Data (client_id, company_name) values (400055, 'Strosin-Crooks');
insert into Client_Data (client_id, company_name) values (400056, 'Toy and Sons');
insert into Client_Data (client_id, company_name) values (400057, 'Wiza, Spencer and Carter');
insert into Client_Data (client_id, company_name) values (400058, 'Effertz, Aufderhar and Koss');
insert into Client_Data (client_id, company_name) values (400059, 'Lynch and Sons');
insert into Client_Data (client_id, company_name) values (400060, 'McDermott Inc');
insert into Client_Data (client_id, company_name) values (400061, 'Ward, Mante and Stamm');
insert into Client_Data (client_id, company_name) values (400062, 'Rowe, Jast and Metz');
insert into Client_Data (client_id, company_name) values (400063, 'Balistreri and Sons');
insert into Client_Data (client_id, company_name) values (400064, 'Eichmann, Reynolds and Jakubowski');
insert into Client_Data (client_id, company_name) values (400065, 'Bins, Donnelly and Hamill');
insert into Client_Data (client_id, company_name) values (400066, 'Corwin Group');
insert into Client_Data (client_id, company_name) values (400067, 'Haley and Sons');
insert into Client_Data (client_id, company_name) values (400068, 'Davis LLC');
insert into Client_Data (client_id, company_name) values (400069, 'Strosin-Howell');
insert into Client_Data (client_id, company_name) values (400070, 'Walter-Torp');
insert into Client_Data (client_id, company_name) values (400071, 'Prosacco-Satterfield');
insert into Client_Data (client_id, company_name) values (400072, 'King-Barrows');
insert into Client_Data (client_id, company_name) values (400073, 'Farrell-Schowalter');
insert into Client_Data (client_id, company_name) values (400074, 'Davis, Green and Schuster');
insert into Client_Data (client_id, company_name) values (400075, 'Kub-O''Reilly');
insert into Client_Data (client_id, company_name) values (400076, 'Hamill, Watsica and Anderson');
insert into Client_Data (client_id, company_name) values (400077, 'Runolfsdottir Group');
insert into Client_Data (client_id, company_name) values (400078, 'Murphy, Beier and Anderson');
insert into Client_Data (client_id, company_name) values (400079, 'Ebert and Sons');
insert into Client_Data (client_id, company_name) values (400080, 'Hahn-Haley');
insert into Client_Data (client_id, company_name) values (400081, 'Schroeder, Kirlin and Schneider');
insert into Client_Data (client_id, company_name) values (400082, 'Wiegand-Hackett');
insert into Client_Data (client_id, company_name) values (400083, 'Turcotte-Rogahn');
insert into Client_Data (client_id, company_name) values (400084, 'Koss-Gutkowski');
insert into Client_Data (client_id, company_name) values (400085, 'Rogahn LLC');
insert into Client_Data (client_id, company_name) values (400086, 'Auer-Green');
insert into Client_Data (client_id, company_name) values (400087, 'Purdy, Casper and Satterfield');
insert into Client_Data (client_id, company_name) values (400088, 'Berge and Sons');
insert into Client_Data (client_id, company_name) values (400089, 'Hodkiewicz Inc');
insert into Client_Data (client_id, company_name) values (400090, 'Farrell-Torp');
insert into Client_Data (client_id, company_name) values (400091, 'Hammes Group');
insert into Client_Data (client_id, company_name) values (400092, 'Wehner, Steuber and Gislason');
insert into Client_Data (client_id, company_name) values (400093, 'Ondricka-Kuvalis');
insert into Client_Data (client_id, company_name) values (400094, 'Cummerata-MacGyver');
insert into Client_Data (client_id, company_name) values (400095, 'Rippin and Sons');
insert into Client_Data (client_id, company_name) values (400096, 'MacGyver-Swaniawski');
insert into Client_Data (client_id, company_name) values (400097, 'Stroman, Donnelly and Blick');
insert into Client_Data (client_id, company_name) values (400098, 'Barrows, Stark and Carter');
insert into Client_Data (client_id, company_name) values (400099, 'Block, Fritsch and Schulist');
insert into Client_Data (client_id, company_name) values (400100, 'Wilkinson LLC');
insert into Client_Data (client_id, company_name) values (400101, 'Prosacco, Wiza and Conn');
insert into Client_Data (client_id, company_name) values (400102, 'Grant, Feest and Feil');
insert into Client_Data (client_id, company_name) values (400103, 'Donnelly-Connelly');
insert into Client_Data (client_id, company_name) values (400104, 'Carroll, Rempel and Ondricka');
insert into Client_Data (client_id, company_name) values (400105, 'Hane-Funk');
insert into Client_Data (client_id, company_name) values (400106, 'Hegmann, Jacobi and Abbott');
insert into Client_Data (client_id, company_name) values (400107, 'Reinger-Sipes');
insert into Client_Data (client_id, company_name) values (400108, 'Metz Inc');
insert into Client_Data (client_id, company_name) values (400109, 'Gerlach-Senger');
insert into Client_Data (client_id, company_name) values (400110, 'Fahey-Schmidt');
insert into Client_Data (client_id, company_name) values (400111, 'Mraz-Upton');
insert into Client_Data (client_id, company_name) values (400112, 'Funk-Harvey');
insert into Client_Data (client_id, company_name) values (400113, 'Buckridge-Morar');
insert into Client_Data (client_id, company_name) values (400114, 'Jakubowski, Sanford and Hudson');
insert into Client_Data (client_id, company_name) values (400115, 'Olson Group');
insert into Client_Data (client_id, company_name) values (400116, 'Mosciski-Willms');
insert into Client_Data (client_id, company_name) values (400117, 'Becker-Little');
insert into Client_Data (client_id, company_name) values (400118, 'DuBuque-Smitham');
insert into Client_Data (client_id, company_name) values (400119, 'Bergstrom-Watsica');
insert into Client_Data (client_id, company_name) values (400120, 'Welch and Sons');
insert into Client_Data (client_id, company_name) values (400121, 'Stehr-Moore');
insert into Client_Data (client_id, company_name) values (400122, 'Barton Inc');
insert into Client_Data (client_id, company_name) values (400123, 'Hodkiewicz and Sons');
insert into Client_Data (client_id, company_name) values (400124, 'Pfannerstill-Toy');
insert into Client_Data (client_id, company_name) values (400125, 'Nienow-Conroy');
insert into Client_Data (client_id, company_name) values (400126, 'Jakubowski-Hartmann');
insert into Client_Data (client_id, company_name) values (400127, 'Steuber, Kuhic and Price');
insert into Client_Data (client_id, company_name) values (400128, 'Rau LLC');
insert into Client_Data (client_id, company_name) values (400129, 'Fisher Inc');
insert into Client_Data (client_id, company_name) values (400130, 'Veum, Hettinger and Rolfson');
insert into Client_Data (client_id, company_name) values (400131, 'Kihn LLC');
insert into Client_Data (client_id, company_name) values (400132, 'Jacobs-Barton');
insert into Client_Data (client_id, company_name) values (400133, 'Bins Inc');
insert into Client_Data (client_id, company_name) values (400134, 'Stiedemann, Walsh and Weber');
insert into Client_Data (client_id, company_name) values (400135, 'Hagenes Group');
insert into Client_Data (client_id, company_name) values (400136, 'Conn-Wilderman');
insert into Client_Data (client_id, company_name) values (400137, 'Yundt Group');
insert into Client_Data (client_id, company_name) values (400138, 'Wyman Inc');
insert into Client_Data (client_id, company_name) values (400139, 'Toy Group');
insert into Client_Data (client_id, company_name) values (400140, 'Hammes-Hand');
insert into Client_Data (client_id, company_name) values (400141, 'Lesch-Cremin');
insert into Client_Data (client_id, company_name) values (400142, 'Sawayn-Stiedemann');
insert into Client_Data (client_id, company_name) values (400143, 'Hyatt and Sons');
insert into Client_Data (client_id, company_name) values (400144, 'Fritsch, Beier and Oberbrunner');
insert into Client_Data (client_id, company_name) values (400145, 'Howe-Macejkovic');
insert into Client_Data (client_id, company_name) values (400146, 'Grimes and Sons');
insert into Client_Data (client_id, company_name) values (400147, 'Heathcote, Rolfson and Pouros');
insert into Client_Data (client_id, company_name) values (400148, 'Orn and Sons');
insert into Client_Data (client_id, company_name) values (400149, 'Doyle-Adams');
insert into Client_Data (client_id, company_name) values (400150, 'Mayert-Dicki');
insert into Client_Data (client_id, company_name) values (400151, 'Hamill and Sons');
insert into Client_Data (client_id, company_name) values (400152, 'Fahey, Hagenes and Streich');
insert into Client_Data (client_id, company_name) values (400153, 'Pfeffer LLC');
insert into Client_Data (client_id, company_name) values (400154, 'Bergnaum, Boyle and Ryan');
insert into Client_Data (client_id, company_name) values (400155, 'Carter and Sons');
insert into Client_Data (client_id, company_name) values (400156, 'Rippin, Auer and Auer');
insert into Client_Data (client_id, company_name) values (400157, 'Vandervort Inc');
insert into Client_Data (client_id, company_name) values (400158, 'Hackett and Sons');
insert into Client_Data (client_id, company_name) values (400159, 'Kihn-Wintheiser');
insert into Client_Data (client_id, company_name) values (400160, 'Cruickshank-Emmerich');
insert into Client_Data (client_id, company_name) values (400161, 'Casper, Bogan and Donnelly');
insert into Client_Data (client_id, company_name) values (400162, 'Murray and Sons');
insert into Client_Data (client_id, company_name) values (400163, 'Bergnaum, Dibbert and Koepp');
insert into Client_Data (client_id, company_name) values (400164, 'Jacobi Group');
insert into Client_Data (client_id, company_name) values (400165, 'Murray, Beier and Carter');
insert into Client_Data (client_id, company_name) values (400166, 'Olson, Schamberger and Predovic');
insert into Client_Data (client_id, company_name) values (400167, 'Greenholt-Dietrich');
insert into Client_Data (client_id, company_name) values (400168, 'Leffler-Murray');
insert into Client_Data (client_id, company_name) values (400169, 'Cummerata-Lowe');
insert into Client_Data (client_id, company_name) values (400170, 'Towne, Jerde and Ziemann');
insert into Client_Data (client_id, company_name) values (400171, 'McClure LLC');
insert into Client_Data (client_id, company_name) values (400172, 'Mohr-Bernhard');
insert into Client_Data (client_id, company_name) values (400173, 'Rice Group');
insert into Client_Data (client_id, company_name) values (400174, 'Grimes-Smith');
insert into Client_Data (client_id, company_name) values (400175, 'McDermott-Ortiz');
insert into Client_Data (client_id, company_name) values (400176, 'Ullrich LLC');
insert into Client_Data (client_id, company_name) values (400177, 'Greenfelder, Boehm and McGlynn');
insert into Client_Data (client_id, company_name) values (400178, 'Goldner, Dickinson and Rutherford');
insert into Client_Data (client_id, company_name) values (400179, 'Cummings-Jerde');
insert into Client_Data (client_id, company_name) values (400180, 'Schaefer-DuBuque');
insert into Client_Data (client_id, company_name) values (400181, 'Legros-Olson');
insert into Client_Data (client_id, company_name) values (400182, 'Kovacek-Connelly');
insert into Client_Data (client_id, company_name) values (400183, 'Moen LLC');
insert into Client_Data (client_id, company_name) values (400184, 'Marvin-Schneider');
insert into Client_Data (client_id, company_name) values (400185, 'Gusikowski-Moore');
insert into Client_Data (client_id, company_name) values (400186, 'Cassin Inc');
insert into Client_Data (client_id, company_name) values (400187, 'Renner Group');
insert into Client_Data (client_id, company_name) values (400188, 'Ledner Inc');
insert into Client_Data (client_id, company_name) values (400189, 'Adams and Sons');
insert into Client_Data (client_id, company_name) values (400190, 'Willms LLC');
insert into Client_Data (client_id, company_name) values (400191, 'Collier LLC');
insert into Client_Data (client_id, company_name) values (400192, 'Marvin-Blanda');
insert into Client_Data (client_id, company_name) values (400193, 'Reichert-Fadel');
insert into Client_Data (client_id, company_name) values (400194, 'Robel and Sons');
insert into Client_Data (client_id, company_name) values (400195, 'Runolfsson and Sons');
insert into Client_Data (client_id, company_name) values (400196, 'Tromp, Mertz and Lubowitz');
insert into Client_Data (client_id, company_name) values (400197, 'Cormier-Kulas');
insert into Client_Data (client_id, company_name) values (400198, 'Trantow, Fahey and Kuhlman');
insert into Client_Data (client_id, company_name) values (400199, 'Schneider-Gleichner');
insert into Client_Data (client_id, company_name) values (400200, 'Pouros, Zieme and Kshlerin');
insert into Client_Data (client_id, company_name) values (400201, 'Gutkowski LLC');
insert into Client_Data (client_id, company_name) values (400202, 'Walker, Johns and Bins');
insert into Client_Data (client_id, company_name) values (400203, 'Vandervort, Keebler and Considine');
insert into Client_Data (client_id, company_name) values (400204, 'Bergnaum-Bergstrom');
insert into Client_Data (client_id, company_name) values (400205, 'Kunde Inc');
insert into Client_Data (client_id, company_name) values (400206, 'Wyman LLC');
insert into Client_Data (client_id, company_name) values (400207, 'Schiller, Halvorson and White');
insert into Client_Data (client_id, company_name) values (400208, 'Boyle, O''Hara and Lesch');
insert into Client_Data (client_id, company_name) values (400209, 'Durgan-Jast');
insert into Client_Data (client_id, company_name) values (400210, 'Altenwerth-Sipes');
insert into Client_Data (client_id, company_name) values (400211, 'Ebert, Gibson and Simonis');
insert into Client_Data (client_id, company_name) values (400212, 'Hintz and Sons');
insert into Client_Data (client_id, company_name) values (400213, 'Cartwright, Fahey and Johnson');
insert into Client_Data (client_id, company_name) values (400214, 'Rolfson, Kohler and Welch');
insert into Client_Data (client_id, company_name) values (400215, 'Funk LLC');
insert into Client_Data (client_id, company_name) values (400216, 'Thiel LLC');
insert into Client_Data (client_id, company_name) values (400217, 'Wiegand-Ernser');
insert into Client_Data (client_id, company_name) values (400218, 'Pollich-Hudson');
insert into Client_Data (client_id, company_name) values (400219, 'Schamberger LLC');
insert into Client_Data (client_id, company_name) values (400220, 'Metz-Schmitt');
insert into Client_Data (client_id, company_name) values (400221, 'Parisian-Turcotte');
insert into Client_Data (client_id, company_name) values (400222, 'Nikolaus LLC');
insert into Client_Data (client_id, company_name) values (400223, 'Towne-Shanahan');
insert into Client_Data (client_id, company_name) values (400224, 'Ondricka, Marquardt and Gusikowski');
insert into Client_Data (client_id, company_name) values (400225, 'Balistreri Inc');
insert into Client_Data (client_id, company_name) values (400226, 'Sporer-Erdman');
insert into Client_Data (client_id, company_name) values (400227, 'Carroll-Hills');
insert into Client_Data (client_id, company_name) values (400228, 'Berge LLC');
insert into Client_Data (client_id, company_name) values (400229, 'Keebler Group');
insert into Client_Data (client_id, company_name) values (400230, 'Hamill-Deckow');
insert into Client_Data (client_id, company_name) values (400231, 'Bernhard-Carter');
insert into Client_Data (client_id, company_name) values (400232, 'Gerhold LLC');
insert into Client_Data (client_id, company_name) values (400233, 'Weimann, Wiegand and Cummings');
insert into Client_Data (client_id, company_name) values (400234, 'Bradtke-Prosacco');
insert into Client_Data (client_id, company_name) values (400235, 'Mohr-Homenick');
insert into Client_Data (client_id, company_name) values (400236, 'Weissnat-Hintz');
insert into Client_Data (client_id, company_name) values (400237, 'Schinner, Sanford and Graham');
insert into Client_Data (client_id, company_name) values (400238, 'Kuhic-Kub');
insert into Client_Data (client_id, company_name) values (400239, 'Simonis and Sons');
insert into Client_Data (client_id, company_name) values (400240, 'Grimes LLC');
insert into Client_Data (client_id, company_name) values (400241, 'Boyer-Feest');
insert into Client_Data (client_id, company_name) values (400242, 'Runolfsdottir, Casper and McGlynn');
insert into Client_Data (client_id, company_name) values (400243, 'Halvorson-Ullrich');
insert into Client_Data (client_id, company_name) values (400244, 'Quigley-Connelly');
insert into Client_Data (client_id, company_name) values (400245, 'Kerluke, Willms and Murazik');
insert into Client_Data (client_id, company_name) values (400246, 'Kerluke, Dickens and Bogisich');
insert into Client_Data (client_id, company_name) values (400247, 'Paucek Group');
insert into Client_Data (client_id, company_name) values (400248, 'Osinski Inc');
insert into Client_Data (client_id, company_name) values (400249, 'Parisian, Batz and Runolfsson');
insert into Client_Data (client_id, company_name) values (400250, 'Baumbach Group');
insert into Client_Data (client_id, company_name) values (400251, 'Stanton, Hoeger and Hoeger');
insert into Client_Data (client_id, company_name) values (400252, 'Legros, Ferry and Ankunding');
insert into Client_Data (client_id, company_name) values (400253, 'Bernhard-Predovic');
insert into Client_Data (client_id, company_name) values (400254, 'Nitzsche and Sons');
insert into Client_Data (client_id, company_name) values (400255, 'Keebler, Kling and Parisian');
insert into Client_Data (client_id, company_name) values (400256, 'Spencer-Turcotte');
insert into Client_Data (client_id, company_name) values (400257, 'Gleason, Schulist and Torphy');
insert into Client_Data (client_id, company_name) values (400258, 'Goodwin LLC');
insert into Client_Data (client_id, company_name) values (400259, 'Kunde Inc');
insert into Client_Data (client_id, company_name) values (400260, 'Cummings-Labadie');
insert into Client_Data (client_id, company_name) values (400261, 'Satterfield and Sons');
insert into Client_Data (client_id, company_name) values (400262, 'Gerhold, Davis and Stanton');
insert into Client_Data (client_id, company_name) values (400263, 'Crist and Sons');
insert into Client_Data (client_id, company_name) values (400264, 'Veum-Quigley');
insert into Client_Data (client_id, company_name) values (400265, 'Reinger, Flatley and Wuckert');
insert into Client_Data (client_id, company_name) values (400266, 'Hintz Group');
insert into Client_Data (client_id, company_name) values (400267, 'Mosciski-Nienow');
insert into Client_Data (client_id, company_name) values (400268, 'McKenzie-Mayert');
insert into Client_Data (client_id, company_name) values (400269, 'Bradtke Inc');
insert into Client_Data (client_id, company_name) values (400270, 'West-Rau');
insert into Client_Data (client_id, company_name) values (400271, 'Sauer-Kirlin');
insert into Client_Data (client_id, company_name) values (400272, 'Dickinson Group');
insert into Client_Data (client_id, company_name) values (400273, 'Abernathy LLC');
insert into Client_Data (client_id, company_name) values (400274, 'Schulist-Hodkiewicz');
insert into Client_Data (client_id, company_name) values (400275, 'Shields and Sons');
insert into Client_Data (client_id, company_name) values (400276, 'Treutel Group');
insert into Client_Data (client_id, company_name) values (400277, 'Schuppe, Kshlerin and Smith');
insert into Client_Data (client_id, company_name) values (400278, 'Schaefer-Carter');
insert into Client_Data (client_id, company_name) values (400279, 'Dibbert-Funk');
insert into Client_Data (client_id, company_name) values (400280, 'Vandervort-Rolfson');
insert into Client_Data (client_id, company_name) values (400281, 'Towne Group');
insert into Client_Data (client_id, company_name) values (400282, 'Russel, Krajcik and Schulist');
insert into Client_Data (client_id, company_name) values (400283, 'Yundt Inc');
insert into Client_Data (client_id, company_name) values (400284, 'Bernhard-Pollich');
insert into Client_Data (client_id, company_name) values (400285, 'Medhurst Group');
insert into Client_Data (client_id, company_name) values (400286, 'O''Hara LLC');
insert into Client_Data (client_id, company_name) values (400287, 'Gottlieb-Blanda');
insert into Client_Data (client_id, company_name) values (400288, 'Prosacco-Cruickshank');
insert into Client_Data (client_id, company_name) values (400289, 'Willms, Upton and Schiller');
insert into Client_Data (client_id, company_name) values (400290, 'Smith and Sons');
insert into Client_Data (client_id, company_name) values (400291, 'Paucek-Dickinson');
insert into Client_Data (client_id, company_name) values (400292, 'Heller Inc');
insert into Client_Data (client_id, company_name) values (400293, 'Vandervort-Reilly');
insert into Client_Data (client_id, company_name) values (400294, 'Kozey Inc');
insert into Client_Data (client_id, company_name) values (400295, 'Smith Inc');
insert into Client_Data (client_id, company_name) values (400296, 'Hyatt-Donnelly');
insert into Client_Data (client_id, company_name) values (400297, 'Lockman LLC');
insert into Client_Data (client_id, company_name) values (400298, 'Wolff, Kerluke and Gutmann');
insert into Client_Data (client_id, company_name) values (400299, 'Beier Inc');
insert into Client_Data (client_id, company_name) values (400300, 'Gerlach LLC');
insert into Client_Data (client_id, company_name) values (400301, 'Yundt and Sons');
insert into Client_Data (client_id, company_name) values (400302, 'Bernhard Group');
insert into Client_Data (client_id, company_name) values (400303, 'McKenzie Inc');
insert into Client_Data (client_id, company_name) values (400304, 'Bergstrom LLC');
insert into Client_Data (client_id, company_name) values (400305, 'Marquardt, Sawayn and Jerde');
insert into Client_Data (client_id, company_name) values (400306, 'Carter and Sons');
insert into Client_Data (client_id, company_name) values (400307, 'Buckridge-Kutch');
insert into Client_Data (client_id, company_name) values (400308, 'Considine and Sons');
insert into Client_Data (client_id, company_name) values (400309, 'Krajcik and Sons');
insert into Client_Data (client_id, company_name) values (400310, 'Rosenbaum, Jakubowski and Lowe');
insert into Client_Data (client_id, company_name) values (400311, 'Hills, Hodkiewicz and Simonis');
insert into Client_Data (client_id, company_name) values (400312, 'Bernhard-Jerde');
insert into Client_Data (client_id, company_name) values (400313, 'Stokes-Jacobs');
insert into Client_Data (client_id, company_name) values (400314, 'Herman and Sons');
insert into Client_Data (client_id, company_name) values (400315, 'Kozey and Sons');
insert into Client_Data (client_id, company_name) values (400316, 'Rippin LLC');
insert into Client_Data (client_id, company_name) values (400317, 'Steuber Group');
insert into Client_Data (client_id, company_name) values (400318, 'Jenkins, Jenkins and Muller');
insert into Client_Data (client_id, company_name) values (400319, 'Dicki-Breitenberg');
insert into Client_Data (client_id, company_name) values (400320, 'Reinger Group');
insert into Client_Data (client_id, company_name) values (400321, 'Flatley LLC');
insert into Client_Data (client_id, company_name) values (400322, 'Jakubowski Inc');
insert into Client_Data (client_id, company_name) values (400323, 'Balistreri-Fay');
insert into Client_Data (client_id, company_name) values (400324, 'Carter LLC');
insert into Client_Data (client_id, company_name) values (400325, 'Sporer-Gulgowski');
insert into Client_Data (client_id, company_name) values (400326, 'Grady, Jacobson and Shanahan');
insert into Client_Data (client_id, company_name) values (400327, 'Kessler Group');
insert into Client_Data (client_id, company_name) values (400328, 'Bergstrom-Russel');
insert into Client_Data (client_id, company_name) values (400329, 'Ratke-Harris');
insert into Client_Data (client_id, company_name) values (400330, 'Conn Inc');
insert into Client_Data (client_id, company_name) values (400331, 'Lind, Reinger and Breitenberg');
insert into Client_Data (client_id, company_name) values (400332, 'Funk-Armstrong');
insert into Client_Data (client_id, company_name) values (400333, 'Parker Group');
insert into Client_Data (client_id, company_name) values (400334, 'Lind Group');
insert into Client_Data (client_id, company_name) values (400335, 'Hudson Group');
insert into Client_Data (client_id, company_name) values (400336, 'Gislason-Swift');
insert into Client_Data (client_id, company_name) values (400337, 'Adams, Sanford and Dare');
insert into Client_Data (client_id, company_name) values (400338, 'Lemke and Sons');
insert into Client_Data (client_id, company_name) values (400339, 'Rodriguez Group');
insert into Client_Data (client_id, company_name) values (400340, 'Daniel, Armstrong and Kulas');
insert into Client_Data (client_id, company_name) values (400341, 'Purdy LLC');
insert into Client_Data (client_id, company_name) values (400342, 'Stracke-Swift');
insert into Client_Data (client_id, company_name) values (400343, 'Waelchi-Turcotte');
insert into Client_Data (client_id, company_name) values (400344, 'Stiedemann-Kemmer');
insert into Client_Data (client_id, company_name) values (400345, 'Nicolas-Ankunding');
insert into Client_Data (client_id, company_name) values (400346, 'Tremblay Group');
insert into Client_Data (client_id, company_name) values (400347, 'Langosh LLC');
insert into Client_Data (client_id, company_name) values (400348, 'Grant-Mayer');
insert into Client_Data (client_id, company_name) values (400349, 'Kris Inc');
insert into Client_Data (client_id, company_name) values (400350, 'Ankunding and Sons');
insert into Client_Data (client_id, company_name) values (400351, 'Rodriguez-Sanford');
insert into Client_Data (client_id, company_name) values (400352, 'Stiedemann and Sons');
insert into Client_Data (client_id, company_name) values (400353, 'Olson Inc');
insert into Client_Data (client_id, company_name) values (400354, 'Fay, Kris and Hegmann');
insert into Client_Data (client_id, company_name) values (400355, 'Schumm-Conroy');
insert into Client_Data (client_id, company_name) values (400356, 'Green-Bode');
insert into Client_Data (client_id, company_name) values (400357, 'Klein, Blanda and O''Keefe');
insert into Client_Data (client_id, company_name) values (400358, 'Skiles-Jakubowski');
insert into Client_Data (client_id, company_name) values (400359, 'Bode-Dooley');
insert into Client_Data (client_id, company_name) values (400360, 'Sawayn, Bailey and Wuckert');
insert into Client_Data (client_id, company_name) values (400361, 'Koepp-Bayer');
insert into Client_Data (client_id, company_name) values (400362, 'Walsh, Roberts and Kris');
insert into Client_Data (client_id, company_name) values (400363, 'Shanahan-Larson');
insert into Client_Data (client_id, company_name) values (400364, 'Smith-Auer');
insert into Client_Data (client_id, company_name) values (400365, 'Larson and Sons');
insert into Client_Data (client_id, company_name) values (400366, 'Flatley and Sons');
insert into Client_Data (client_id, company_name) values (400367, 'McDermott-Grant');
insert into Client_Data (client_id, company_name) values (400368, 'Sawayn, Sauer and Kerluke');
insert into Client_Data (client_id, company_name) values (400369, 'Mills-Bartoletti');
insert into Client_Data (client_id, company_name) values (400370, 'Medhurst-Denesik');
insert into Client_Data (client_id, company_name) values (400371, 'Romaguera, Wisozk and Goyette');
insert into Client_Data (client_id, company_name) values (400372, 'Cormier, Hagenes and Hahn');
insert into Client_Data (client_id, company_name) values (400373, 'Balistreri Group');
insert into Client_Data (client_id, company_name) values (400374, 'Koepp, Aufderhar and Schaefer');
insert into Client_Data (client_id, company_name) values (400375, 'Stroman-Crooks');
insert into Client_Data (client_id, company_name) values (400376, 'Kreiger, Bednar and Aufderhar');
insert into Client_Data (client_id, company_name) values (400377, 'Rippin Inc');
insert into Client_Data (client_id, company_name) values (400378, 'Bosco LLC');
insert into Client_Data (client_id, company_name) values (400379, 'Bradtke, Will and Wyman');
insert into Client_Data (client_id, company_name) values (400380, 'Considine-Miller');
insert into Client_Data (client_id, company_name) values (400381, 'Willms LLC');
insert into Client_Data (client_id, company_name) values (400382, 'Purdy, Kuhn and Johns');
insert into Client_Data (client_id, company_name) values (400383, 'McCullough Inc');
insert into Client_Data (client_id, company_name) values (400384, 'Stamm-Haag');
insert into Client_Data (client_id, company_name) values (400385, 'Reichert-Rowe');
insert into Client_Data (client_id, company_name) values (400386, 'Rau, Kohler and Hessel');
insert into Client_Data (client_id, company_name) values (400387, 'Weimann and Sons');
insert into Client_Data (client_id, company_name) values (400388, 'Schuster and Sons');
insert into Client_Data (client_id, company_name) values (400389, 'Abbott, Kunde and Hudson');
insert into Client_Data (client_id, company_name) values (400390, 'Morar-Lubowitz');
insert into Client_Data (client_id, company_name) values (400391, 'O''Conner Group');
insert into Client_Data (client_id, company_name) values (400392, 'Collins-Dare');
insert into Client_Data (client_id, company_name) values (400393, 'Mohr-Ledner');
insert into Client_Data (client_id, company_name) values (400394, 'Mante, Johns and McLaughlin');
insert into Client_Data (client_id, company_name) values (400395, 'Jerde-Weimann');
insert into Client_Data (client_id, company_name) values (400396, 'Gutmann Group');
insert into Client_Data (client_id, company_name) values (400397, 'Jacobi-Feeney');
insert into Client_Data (client_id, company_name) values (400398, 'Halvorson-Bartoletti');
insert into Client_Data (client_id, company_name) values (400399, 'McDermott Group');
insert into Client_Data (client_id, company_name) values (400400, 'Stracke-Prosacco');
insert into Client_Data (client_id, company_name) values (400401, 'Ledner, Schimmel and Huels');
insert into Client_Data (client_id, company_name) values (400402, 'Borer, Nicolas and Ward');
insert into Client_Data (client_id, company_name) values (400403, 'Hamill, Halvorson and Effertz');
insert into Client_Data (client_id, company_name) values (400404, 'Hintz, Morar and Wuckert');
insert into Client_Data (client_id, company_name) values (400405, 'Weber and Sons');
insert into Client_Data (client_id, company_name) values (400406, 'Schultz, Beier and Schowalter');
insert into Client_Data (client_id, company_name) values (400407, 'Flatley, Gleichner and Hegmann');
insert into Client_Data (client_id, company_name) values (400408, 'Kreiger, Moore and Berge');
insert into Client_Data (client_id, company_name) values (400409, 'Durgan-Hilpert');
insert into Client_Data (client_id, company_name) values (400410, 'Torp-Stark');
insert into Client_Data (client_id, company_name) values (400411, 'Rippin, Wisoky and Stiedemann');
insert into Client_Data (client_id, company_name) values (400412, 'Shields, Kreiger and Gibson');
insert into Client_Data (client_id, company_name) values (400413, 'Labadie Inc');
insert into Client_Data (client_id, company_name) values (400414, 'Jaskolski-Herzog');
insert into Client_Data (client_id, company_name) values (400415, 'Spinka Inc');
insert into Client_Data (client_id, company_name) values (400416, 'Lindgren Inc');
insert into Client_Data (client_id, company_name) values (400417, 'Maggio-Toy');
insert into Client_Data (client_id, company_name) values (400418, 'Borer LLC');
insert into Client_Data (client_id, company_name) values (400419, 'Frami LLC');
insert into Client_Data (client_id, company_name) values (400420, 'VonRueden-Fritsch');
insert into Client_Data (client_id, company_name) values (400421, 'Predovic, Friesen and Terry');
insert into Client_Data (client_id, company_name) values (400422, 'Aufderhar-Roob');
insert into Client_Data (client_id, company_name) values (400423, 'Bogisich Group');
insert into Client_Data (client_id, company_name) values (400424, 'Heathcote, Aufderhar and Stanton');
insert into Client_Data (client_id, company_name) values (400425, 'Grady-Wilderman');
insert into Client_Data (client_id, company_name) values (400426, 'Spencer-Stanton');
insert into Client_Data (client_id, company_name) values (400427, 'Balistreri LLC');
insert into Client_Data (client_id, company_name) values (400428, 'Streich Inc');
insert into Client_Data (client_id, company_name) values (400429, 'Miller, Rath and MacGyver');
insert into Client_Data (client_id, company_name) values (400430, 'Keebler Inc');
insert into Client_Data (client_id, company_name) values (400431, 'Eichmann-Armstrong');
insert into Client_Data (client_id, company_name) values (400432, 'Cartwright Group');
insert into Client_Data (client_id, company_name) values (400433, 'Satterfield Inc');
insert into Client_Data (client_id, company_name) values (400434, 'Streich Inc');
insert into Client_Data (client_id, company_name) values (400435, 'Mohr Group');
insert into Client_Data (client_id, company_name) values (400436, 'Koch-Bruen');
insert into Client_Data (client_id, company_name) values (400437, 'DuBuque-Waters');
insert into Client_Data (client_id, company_name) values (400438, 'Wolff-Graham');
insert into Client_Data (client_id, company_name) values (400439, 'Beahan, Satterfield and Weimann');
insert into Client_Data (client_id, company_name) values (400440, 'Mayer-Durgan');
insert into Client_Data (client_id, company_name) values (400441, 'Doyle Group');
insert into Client_Data (client_id, company_name) values (400442, 'Zulauf-Fahey');
insert into Client_Data (client_id, company_name) values (400443, 'Windler Inc');
insert into Client_Data (client_id, company_name) values (400444, 'Wolff-Goodwin');
insert into Client_Data (client_id, company_name) values (400445, 'Mayert-D''Amore');
insert into Client_Data (client_id, company_name) values (400446, 'Mitchell Inc');
insert into Client_Data (client_id, company_name) values (400447, 'Dickens-Homenick');
insert into Client_Data (client_id, company_name) values (400448, 'Tromp, Wiza and Hegmann');
insert into Client_Data (client_id, company_name) values (400449, 'Gerhold Group');
insert into Client_Data (client_id, company_name) values (400450, 'Little, Macejkovic and Hansen');
insert into Client_Data (client_id, company_name) values (400451, 'Ziemann-Waters');
insert into Client_Data (client_id, company_name) values (400452, 'Smith-Casper');
insert into Client_Data (client_id, company_name) values (400453, 'Reinger-Jacobi');
insert into Client_Data (client_id, company_name) values (400454, 'Lebsack and Sons');
insert into Client_Data (client_id, company_name) values (400455, 'Emard Inc');
insert into Client_Data (client_id, company_name) values (400456, 'Rice Inc');
insert into Client_Data (client_id, company_name) values (400457, 'Kerluke, Bednar and Rolfson');
insert into Client_Data (client_id, company_name) values (400458, 'Block, Johns and Conn');
insert into Client_Data (client_id, company_name) values (400459, 'Johns-Wuckert');
insert into Client_Data (client_id, company_name) values (400460, 'Beatty-Mayer');
insert into Client_Data (client_id, company_name) values (400461, 'Hudson and Sons');
insert into Client_Data (client_id, company_name) values (400462, 'Williamson, Walker and Balistreri');
insert into Client_Data (client_id, company_name) values (400463, 'Gleichner-Goodwin');
insert into Client_Data (client_id, company_name) values (400464, 'Mosciski, Fritsch and DuBuque');
insert into Client_Data (client_id, company_name) values (400465, 'Murazik, MacGyver and Keebler');
insert into Client_Data (client_id, company_name) values (400466, 'MacGyver and Sons');
insert into Client_Data (client_id, company_name) values (400467, 'Runte, Breitenberg and Dooley');
insert into Client_Data (client_id, company_name) values (400468, 'Kreiger Group');
insert into Client_Data (client_id, company_name) values (400469, 'Marks LLC');
insert into Client_Data (client_id, company_name) values (400470, 'Bogisich and Sons');
insert into Client_Data (client_id, company_name) values (400471, 'Luettgen, Jacobs and Littel');
insert into Client_Data (client_id, company_name) values (400472, 'Bergstrom Group');
insert into Client_Data (client_id, company_name) values (400473, 'Heaney LLC');
insert into Client_Data (client_id, company_name) values (400474, 'Senger, Heidenreich and Vandervort');
insert into Client_Data (client_id, company_name) values (400475, 'Stroman and Sons');
insert into Client_Data (client_id, company_name) values (400476, 'Hintz, Greenfelder and Corwin');
insert into Client_Data (client_id, company_name) values (400477, 'Conroy-Ernser');
insert into Client_Data (client_id, company_name) values (400478, 'Mills-Kutch');
insert into Client_Data (client_id, company_name) values (400479, 'Heaney, Beier and Walker');
insert into Client_Data (client_id, company_name) values (400480, 'Lind-Jacobs');
insert into Client_Data (client_id, company_name) values (400481, 'Deckow-Frami');
insert into Client_Data (client_id, company_name) values (400482, 'Baumbach-Lind');
insert into Client_Data (client_id, company_name) values (400483, 'Kulas-Friesen');
insert into Client_Data (client_id, company_name) values (400484, 'Erdman, Hyatt and Nolan');
insert into Client_Data (client_id, company_name) values (400485, 'Kuhic LLC');
insert into Client_Data (client_id, company_name) values (400486, 'Schamberger and Sons');
insert into Client_Data (client_id, company_name) values (400487, 'Lebsack Inc');
insert into Client_Data (client_id, company_name) values (400488, 'McGlynn, Robel and Terry');
insert into Client_Data (client_id, company_name) values (400489, 'Runte, Hackett and Stracke');
insert into Client_Data (client_id, company_name) values (400490, 'Sporer, Gleason and Bahringer');
insert into Client_Data (client_id, company_name) values (400491, 'Runolfsdottir-Jacobson');
insert into Client_Data (client_id, company_name) values (400492, 'Frami and Sons');
insert into Client_Data (client_id, company_name) values (400493, 'Rowe-Kunde');
insert into Client_Data (client_id, company_name) values (400494, 'Farrell-Lesch');
insert into Client_Data (client_id, company_name) values (400495, 'Bergnaum, Rohan and Grady');
insert into Client_Data (client_id, company_name) values (400496, 'Block-Kihn');
insert into Client_Data (client_id, company_name) values (400497, 'Rempel, Hayes and Greenholt');
insert into Client_Data (client_id, company_name) values (400498, 'Trantow, Harris and Predovic');
insert into Client_Data (client_id, company_name) values (400499, 'Bechtelar-Green');
insert into Client_Data (client_id, company_name) values (400500, 'Ebert Inc');
insert into Client_Data (client_id, company_name) values (400501, 'Mayert LLC');
insert into Client_Data (client_id, company_name) values (400502, 'Blick Group');
insert into Client_Data (client_id, company_name) values (400503, 'Lueilwitz, Johnson and Weimann');
insert into Client_Data (client_id, company_name) values (400504, 'Hermiston-Konopelski');
insert into Client_Data (client_id, company_name) values (400505, 'Price, Mohr and Watsica');
insert into Client_Data (client_id, company_name) values (400506, 'Leffler, Rice and Lesch');
insert into Client_Data (client_id, company_name) values (400507, 'Kuhlman-Kulas');
insert into Client_Data (client_id, company_name) values (400508, 'Johnson, Lowe and Yundt');
insert into Client_Data (client_id, company_name) values (400509, 'Schuster-Kessler');
insert into Client_Data (client_id, company_name) values (400510, 'Simonis, Jacobs and Kassulke');
insert into Client_Data (client_id, company_name) values (400511, 'Padberg and Sons');
insert into Client_Data (client_id, company_name) values (400512, 'Hayes Inc');
insert into Client_Data (client_id, company_name) values (400513, 'Hackett, Tillman and Senger');
insert into Client_Data (client_id, company_name) values (400514, 'Krajcik-Fay');
insert into Client_Data (client_id, company_name) values (400515, 'Walter and Sons');
insert into Client_Data (client_id, company_name) values (400516, 'Rosenbaum, Dicki and MacGyver');
insert into Client_Data (client_id, company_name) values (400517, 'Pagac Group');
insert into Client_Data (client_id, company_name) values (400518, 'Frami Group');
insert into Client_Data (client_id, company_name) values (400519, 'Murray, Morar and Aufderhar');
insert into Client_Data (client_id, company_name) values (400520, 'Treutel Group');
insert into Client_Data (client_id, company_name) values (400521, 'Windler, Kiehn and Mosciski');
insert into Client_Data (client_id, company_name) values (400522, 'Ledner and Sons');
insert into Client_Data (client_id, company_name) values (400523, 'Pollich Inc');
insert into Client_Data (client_id, company_name) values (400524, 'Dare-Weissnat');
insert into Client_Data (client_id, company_name) values (400525, 'Nitzsche Inc');
insert into Client_Data (client_id, company_name) values (400526, 'Shanahan and Sons');
insert into Client_Data (client_id, company_name) values (400527, 'Lakin, Ortiz and Hegmann');
insert into Client_Data (client_id, company_name) values (400528, 'Wehner Inc');
insert into Client_Data (client_id, company_name) values (400529, 'Ratke-Carroll');
insert into Client_Data (client_id, company_name) values (400530, 'Greenfelder, Rutherford and Borer');
insert into Client_Data (client_id, company_name) values (400531, 'Daugherty Group');
insert into Client_Data (client_id, company_name) values (400532, 'Hessel LLC');
insert into Client_Data (client_id, company_name) values (400533, 'Kling, Franecki and Kohler');
insert into Client_Data (client_id, company_name) values (400534, 'Blick, Haley and Murazik');
insert into Client_Data (client_id, company_name) values (400535, 'Heller Group');
insert into Client_Data (client_id, company_name) values (400536, 'Reichert-Thompson');
insert into Client_Data (client_id, company_name) values (400537, 'Marquardt Inc');
insert into Client_Data (client_id, company_name) values (400538, 'Prosacco, Hamill and Pouros');
insert into Client_Data (client_id, company_name) values (400539, 'Hintz, Runte and Fahey');
insert into Client_Data (client_id, company_name) values (400540, 'Murray-Lindgren');
insert into Client_Data (client_id, company_name) values (400541, 'Quigley-Hilpert');
insert into Client_Data (client_id, company_name) values (400542, 'Wiegand and Sons');
insert into Client_Data (client_id, company_name) values (400543, 'Streich-O''Conner');
insert into Client_Data (client_id, company_name) values (400544, 'Kuvalis Group');
insert into Client_Data (client_id, company_name) values (400545, 'Powlowski, Volkman and Denesik');
insert into Client_Data (client_id, company_name) values (400546, 'Emard-Anderson');
insert into Client_Data (client_id, company_name) values (400547, 'Crist-Bernier');
insert into Client_Data (client_id, company_name) values (400548, 'Kirlin, Rice and Rodriguez');
insert into Client_Data (client_id, company_name) values (400549, 'Lehner Inc');
insert into Client_Data (client_id, company_name) values (400550, 'Grant LLC');
insert into Client_Data (client_id, company_name) values (400551, 'Pouros, Boehm and Abernathy');
insert into Client_Data (client_id, company_name) values (400552, 'Ziemann-Sauer');
insert into Client_Data (client_id, company_name) values (400553, 'Kulas, Brekke and Bauch');
insert into Client_Data (client_id, company_name) values (400554, 'Towne-Hagenes');
insert into Client_Data (client_id, company_name) values (400555, 'Morar, Carter and Torphy');
insert into Client_Data (client_id, company_name) values (400556, 'Bosco LLC');
insert into Client_Data (client_id, company_name) values (400557, 'Schaden-Goodwin');
insert into Client_Data (client_id, company_name) values (400558, 'Cormier, Ondricka and Breitenberg');
insert into Client_Data (client_id, company_name) values (400559, 'Langosh-Daniel');
insert into Client_Data (client_id, company_name) values (400560, 'Bailey LLC');
insert into Client_Data (client_id, company_name) values (400561, 'Zieme-Leuschke');
insert into Client_Data (client_id, company_name) values (400562, 'Bechtelar Group');
insert into Client_Data (client_id, company_name) values (400563, 'Conroy Group');
insert into Client_Data (client_id, company_name) values (400564, 'McClure, Mayert and Schmitt');
insert into Client_Data (client_id, company_name) values (400565, 'Lindgren and Sons');
insert into Client_Data (client_id, company_name) values (400566, 'Rosenbaum and Sons');
insert into Client_Data (client_id, company_name) values (400567, 'Prohaska Group');
insert into Client_Data (client_id, company_name) values (400568, 'Armstrong and Sons');
insert into Client_Data (client_id, company_name) values (400569, 'Rogahn-Mayer');
insert into Client_Data (client_id, company_name) values (400570, 'Schumm, Cummerata and Batz');
insert into Client_Data (client_id, company_name) values (400571, 'Schaefer Inc');
insert into Client_Data (client_id, company_name) values (400572, 'Mraz-Walker');
insert into Client_Data (client_id, company_name) values (400573, 'Volkman, Upton and Ryan');
insert into Client_Data (client_id, company_name) values (400574, 'McClure-Ernser');
insert into Client_Data (client_id, company_name) values (400575, 'McDermott-Cartwright');
insert into Client_Data (client_id, company_name) values (400576, 'Waelchi-Price');
insert into Client_Data (client_id, company_name) values (400577, 'Pagac Group');
insert into Client_Data (client_id, company_name) values (400578, 'Kuvalis Inc');
insert into Client_Data (client_id, company_name) values (400579, 'Pagac-Champlin');
insert into Client_Data (client_id, company_name) values (400580, 'McDermott-Grant');
insert into Client_Data (client_id, company_name) values (400581, 'Schmeler-Johnson');
insert into Client_Data (client_id, company_name) values (400582, 'Torp-Walker');
insert into Client_Data (client_id, company_name) values (400583, 'Klocko LLC');
insert into Client_Data (client_id, company_name) values (400584, 'Senger, Berge and Prosacco');
insert into Client_Data (client_id, company_name) values (400585, 'Rippin Inc');
insert into Client_Data (client_id, company_name) values (400586, 'Buckridge-Gislason');
insert into Client_Data (client_id, company_name) values (400587, 'Quigley Inc');
insert into Client_Data (client_id, company_name) values (400588, 'Schowalter, Moore and Lesch');
insert into Client_Data (client_id, company_name) values (400589, 'Crooks-D''Amore');
insert into Client_Data (client_id, company_name) values (400590, 'Crooks-Berge');
insert into Client_Data (client_id, company_name) values (400591, 'Hoeger, Miller and Breitenberg');
insert into Client_Data (client_id, company_name) values (400592, 'Armstrong, Dietrich and Schinner');
insert into Client_Data (client_id, company_name) values (400593, 'DuBuque Inc');
insert into Client_Data (client_id, company_name) values (400594, 'Kris and Sons');
insert into Client_Data (client_id, company_name) values (400595, 'Koepp-Ryan');
insert into Client_Data (client_id, company_name) values (400596, 'Lang, Kuhn and Skiles');
insert into Client_Data (client_id, company_name) values (400597, 'Roberts Inc');
insert into Client_Data (client_id, company_name) values (400598, 'Simonis Group');
insert into Client_Data (client_id, company_name) values (400599, 'Durgan-Hessel');
insert into Client_Data (client_id, company_name) values (400600, 'Gusikowski-Kutch');
insert into Client_Data (client_id, company_name) values (400601, 'Doyle, Marks and Heller');
insert into Client_Data (client_id, company_name) values (400602, 'Heidenreich LLC');
insert into Client_Data (client_id, company_name) values (400603, 'Hodkiewicz and Sons');
insert into Client_Data (client_id, company_name) values (400604, 'Mante-Carroll');
insert into Client_Data (client_id, company_name) values (400605, 'Schuster-Marquardt');
insert into Client_Data (client_id, company_name) values (400606, 'Bailey Inc');
insert into Client_Data (client_id, company_name) values (400607, 'Dare-Lebsack');
insert into Client_Data (client_id, company_name) values (400608, 'Kuvalis and Sons');
insert into Client_Data (client_id, company_name) values (400609, 'Dooley, Toy and Wehner');
insert into Client_Data (client_id, company_name) values (400610, 'Hermiston, Bartoletti and Kiehn');
insert into Client_Data (client_id, company_name) values (400611, 'D''Amore-Shields');
insert into Client_Data (client_id, company_name) values (400612, 'Luettgen-Farrell');
insert into Client_Data (client_id, company_name) values (400613, 'Jones LLC');
insert into Client_Data (client_id, company_name) values (400614, 'Hagenes, Wisoky and Jakubowski');
insert into Client_Data (client_id, company_name) values (400615, 'Trantow-Grant');
insert into Client_Data (client_id, company_name) values (400616, 'Veum and Sons');
insert into Client_Data (client_id, company_name) values (400617, 'Stracke-Dickinson');
insert into Client_Data (client_id, company_name) values (400618, 'Graham, Champlin and Kuvalis');
insert into Client_Data (client_id, company_name) values (400619, 'Ryan-Beahan');
insert into Client_Data (client_id, company_name) values (400620, 'Bergstrom, Ondricka and Blick');
insert into Client_Data (client_id, company_name) values (400621, 'Armstrong-Harris');
insert into Client_Data (client_id, company_name) values (400622, 'King, Brakus and Morissette');
insert into Client_Data (client_id, company_name) values (400623, 'Nikolaus-Ortiz');
insert into Client_Data (client_id, company_name) values (400624, 'Corwin, Kessler and Dibbert');
insert into Client_Data (client_id, company_name) values (400625, 'Rogahn, Baumbach and Vandervort');
insert into Client_Data (client_id, company_name) values (400626, 'Schmidt-Johnston');
insert into Client_Data (client_id, company_name) values (400627, 'Cole-Bartell');
insert into Client_Data (client_id, company_name) values (400628, 'Tillman, Bins and Kohler');
insert into Client_Data (client_id, company_name) values (400629, 'O''Conner-Schroeder');
insert into Client_Data (client_id, company_name) values (400630, 'Lowe and Sons');
insert into Client_Data (client_id, company_name) values (400631, 'Fay and Sons');
insert into Client_Data (client_id, company_name) values (400632, 'Romaguera, Leffler and Miller');
insert into Client_Data (client_id, company_name) values (400633, 'Jacobs-Oberbrunner');
insert into Client_Data (client_id, company_name) values (400634, 'Kohler Inc');
insert into Client_Data (client_id, company_name) values (400635, 'Heidenreich Group');
insert into Client_Data (client_id, company_name) values (400636, 'Greenholt, Moore and Bailey');
insert into Client_Data (client_id, company_name) values (400637, 'Streich, Schultz and Ortiz');
insert into Client_Data (client_id, company_name) values (400638, 'Volkman Group');
insert into Client_Data (client_id, company_name) values (400639, 'Lowe LLC');
insert into Client_Data (client_id, company_name) values (400640, 'Wisozk-Klein');
insert into Client_Data (client_id, company_name) values (400641, 'Stoltenberg Group');
insert into Client_Data (client_id, company_name) values (400642, 'Ruecker Inc');
insert into Client_Data (client_id, company_name) values (400643, 'Krajcik-Beer');
insert into Client_Data (client_id, company_name) values (400644, 'Dibbert-Bruen');
insert into Client_Data (client_id, company_name) values (400645, 'Welch Group');
insert into Client_Data (client_id, company_name) values (400646, 'Wiza-Hintz');
insert into Client_Data (client_id, company_name) values (400647, 'Bernier, Erdman and Roob');
insert into Client_Data (client_id, company_name) values (400648, 'Kozey LLC');
insert into Client_Data (client_id, company_name) values (400649, 'Crona-Roberts');
insert into Client_Data (client_id, company_name) values (400650, 'O''Conner Inc');
insert into Client_Data (client_id, company_name) values (400651, 'Haag-Mayert');
insert into Client_Data (client_id, company_name) values (400652, 'Medhurst LLC');
insert into Client_Data (client_id, company_name) values (400653, 'Pouros, Kirlin and Bogisich');
insert into Client_Data (client_id, company_name) values (400654, 'Quigley, Parisian and Hagenes');
insert into Client_Data (client_id, company_name) values (400655, 'Swaniawski, Satterfield and Macejkovic');
insert into Client_Data (client_id, company_name) values (400656, 'McKenzie Group');
insert into Client_Data (client_id, company_name) values (400657, 'Zulauf Group');
insert into Client_Data (client_id, company_name) values (400658, 'Klein LLC');
insert into Client_Data (client_id, company_name) values (400659, 'Miller Inc');
insert into Client_Data (client_id, company_name) values (400660, 'Rice LLC');
insert into Client_Data (client_id, company_name) values (400661, 'Nicolas, Legros and Tromp');
insert into Client_Data (client_id, company_name) values (400662, 'Klocko, Tillman and Harvey');
insert into Client_Data (client_id, company_name) values (400663, 'Grimes, Goodwin and Adams');
insert into Client_Data (client_id, company_name) values (400664, 'Connelly, Mertz and Friesen');
insert into Client_Data (client_id, company_name) values (400665, 'Goodwin-West');
insert into Client_Data (client_id, company_name) values (400666, 'Wintheiser, Farrell and Lindgren');
insert into Client_Data (client_id, company_name) values (400667, 'Lueilwitz, Streich and Daniel');
insert into Client_Data (client_id, company_name) values (400668, 'Roob, Gutmann and Reynolds');
insert into Client_Data (client_id, company_name) values (400669, 'Kassulke Inc');
insert into Client_Data (client_id, company_name) values (400670, 'Smith and Sons');
insert into Client_Data (client_id, company_name) values (400671, 'Lubowitz and Sons');
insert into Client_Data (client_id, company_name) values (400672, 'Lehner and Sons');
insert into Client_Data (client_id, company_name) values (400673, 'Grady and Sons');
insert into Client_Data (client_id, company_name) values (400674, 'Blanda Group');
insert into Client_Data (client_id, company_name) values (400675, 'McGlynn-Hammes');
insert into Client_Data (client_id, company_name) values (400676, 'Moen Inc');
insert into Client_Data (client_id, company_name) values (400677, 'Quitzon, Schamberger and Little');
insert into Client_Data (client_id, company_name) values (400678, 'Legros Group');
insert into Client_Data (client_id, company_name) values (400679, 'Abshire-D''Amore');
insert into Client_Data (client_id, company_name) values (400680, 'Kub LLC');
insert into Client_Data (client_id, company_name) values (400681, 'Fahey-Considine');
insert into Client_Data (client_id, company_name) values (400682, 'Nolan-Purdy');
insert into Client_Data (client_id, company_name) values (400683, 'Klocko-McDermott');
insert into Client_Data (client_id, company_name) values (400684, 'O''Keefe, Johns and Armstrong');
insert into Client_Data (client_id, company_name) values (400685, 'Kovacek-Goldner');
insert into Client_Data (client_id, company_name) values (400686, 'Marks-Shanahan');
insert into Client_Data (client_id, company_name) values (400687, 'Schmitt, Schneider and Murphy');
insert into Client_Data (client_id, company_name) values (400688, 'Welch Group');
insert into Client_Data (client_id, company_name) values (400689, 'Nitzsche, Johnson and Kling');
insert into Client_Data (client_id, company_name) values (400690, 'Pagac Group');
insert into Client_Data (client_id, company_name) values (400691, 'Romaguera, Walter and Rice');
insert into Client_Data (client_id, company_name) values (400692, 'Aufderhar, Stark and Paucek');
insert into Client_Data (client_id, company_name) values (400693, 'Beatty and Sons');
insert into Client_Data (client_id, company_name) values (400694, 'Blick, Heathcote and Marvin');
insert into Client_Data (client_id, company_name) values (400695, 'Wolff-Lemke');
insert into Client_Data (client_id, company_name) values (400696, 'Nolan Inc');
insert into Client_Data (client_id, company_name) values (400697, 'Jerde, Schuster and Witting');
insert into Client_Data (client_id, company_name) values (400698, 'Wyman and Sons');
insert into Client_Data (client_id, company_name) values (400699, 'Feeney and Sons');
insert into Client_Data (client_id, company_name) values (400700, 'Erdman-Schamberger');
insert into Client_Data (client_id, company_name) values (400701, 'Prohaska Group');
insert into Client_Data (client_id, company_name) values (400702, 'Denesik, Quigley and Torphy');
insert into Client_Data (client_id, company_name) values (400703, 'Frami, Kutch and Hoeger');
insert into Client_Data (client_id, company_name) values (400704, 'Dickinson-Fritsch');
insert into Client_Data (client_id, company_name) values (400705, 'Langworth-Upton');
insert into Client_Data (client_id, company_name) values (400706, 'Raynor-Hermiston');
insert into Client_Data (client_id, company_name) values (400707, 'Lockman LLC');
insert into Client_Data (client_id, company_name) values (400708, 'Osinski, McKenzie and Collier');
insert into Client_Data (client_id, company_name) values (400709, 'Heidenreich LLC');
insert into Client_Data (client_id, company_name) values (400710, 'Botsford, Barton and Wuckert');
insert into Client_Data (client_id, company_name) values (400711, 'Reichel and Sons');
insert into Client_Data (client_id, company_name) values (400712, 'Kiehn and Sons');
insert into Client_Data (client_id, company_name) values (400713, 'Wiegand Group');
insert into Client_Data (client_id, company_name) values (400714, 'Doyle and Sons');
insert into Client_Data (client_id, company_name) values (400715, 'Marquardt, Reynolds and Brekke');
insert into Client_Data (client_id, company_name) values (400716, 'Thompson-Paucek');
insert into Client_Data (client_id, company_name) values (400717, 'Heathcote, Robel and Mueller');
insert into Client_Data (client_id, company_name) values (400718, 'Deckow, Dickinson and Marvin');
insert into Client_Data (client_id, company_name) values (400719, 'Lowe, Conn and Heidenreich');
insert into Client_Data (client_id, company_name) values (400720, 'Erdman, Kassulke and Rohan');
insert into Client_Data (client_id, company_name) values (400721, 'Ondricka-Zboncak');
insert into Client_Data (client_id, company_name) values (400722, 'Hagenes-Mohr');
insert into Client_Data (client_id, company_name) values (400723, 'Beatty Group');
insert into Client_Data (client_id, company_name) values (400724, 'Runte, Hilll and O''Reilly');
insert into Client_Data (client_id, company_name) values (400725, 'Sanford-McLaughlin');
insert into Client_Data (client_id, company_name) values (400726, 'Conn-Kihn');
insert into Client_Data (client_id, company_name) values (400727, 'Bergstrom and Sons');
insert into Client_Data (client_id, company_name) values (400728, 'Jerde Group');
insert into Client_Data (client_id, company_name) values (400729, 'Mitchell-Wehner');
insert into Client_Data (client_id, company_name) values (400730, 'Prosacco, Farrell and Marks');
insert into Client_Data (client_id, company_name) values (400731, 'Prosacco, Fay and Stokes');
insert into Client_Data (client_id, company_name) values (400732, 'Beahan, Collins and Prohaska');
insert into Client_Data (client_id, company_name) values (400733, 'Reinger LLC');
insert into Client_Data (client_id, company_name) values (400734, 'Gorczany Inc');
insert into Client_Data (client_id, company_name) values (400735, 'Leannon Inc');
insert into Client_Data (client_id, company_name) values (400736, 'Stracke-Conn');
insert into Client_Data (client_id, company_name) values (400737, 'Nitzsche Group');
insert into Client_Data (client_id, company_name) values (400738, 'McLaughlin-Stracke');
insert into Client_Data (client_id, company_name) values (400739, 'Smith-Hintz');
insert into Client_Data (client_id, company_name) values (400740, 'Bernhard LLC');
insert into Client_Data (client_id, company_name) values (400741, 'Batz and Sons');
insert into Client_Data (client_id, company_name) values (400742, 'Rolfson-Hills');
insert into Client_Data (client_id, company_name) values (400743, 'Erdman, Roberts and Lehner');
insert into Client_Data (client_id, company_name) values (400744, 'Stanton Group');
insert into Client_Data (client_id, company_name) values (400745, 'Gleason Group');
insert into Client_Data (client_id, company_name) values (400746, 'Wolff-Ferry');
insert into Client_Data (client_id, company_name) values (400747, 'Nikolaus and Sons');
insert into Client_Data (client_id, company_name) values (400748, 'Kunde, Bechtelar and Runte');
insert into Client_Data (client_id, company_name) values (400749, 'Hintz-Shanahan');
insert into Client_Data (client_id, company_name) values (400750, 'Howell-Lang');
insert into Client_Data (client_id, company_name) values (400751, 'Kutch-Hammes');
insert into Client_Data (client_id, company_name) values (400752, 'Jacobson Group');
insert into Client_Data (client_id, company_name) values (400753, 'Windler, VonRueden and Durgan');
insert into Client_Data (client_id, company_name) values (400754, 'Gerhold, Quitzon and Emmerich');
insert into Client_Data (client_id, company_name) values (400755, 'Eichmann Group');
insert into Client_Data (client_id, company_name) values (400756, 'Cruickshank, Dickinson and Upton');
insert into Client_Data (client_id, company_name) values (400757, 'McClure-Halvorson');
insert into Client_Data (client_id, company_name) values (400758, 'Reinger-Weimann');
insert into Client_Data (client_id, company_name) values (400759, 'Haley Inc');
insert into Client_Data (client_id, company_name) values (400760, 'Raynor, Champlin and Schumm');
insert into Client_Data (client_id, company_name) values (400761, 'Kulas, Farrell and Feeney');
insert into Client_Data (client_id, company_name) values (400762, 'Tremblay, McGlynn and Collier');
insert into Client_Data (client_id, company_name) values (400763, 'Feil-Green');
insert into Client_Data (client_id, company_name) values (400764, 'Powlowski-Beer');
insert into Client_Data (client_id, company_name) values (400765, 'Osinski and Sons');
insert into Client_Data (client_id, company_name) values (400766, 'Beer and Sons');
insert into Client_Data (client_id, company_name) values (400767, 'Runolfsdottir Group');
insert into Client_Data (client_id, company_name) values (400768, 'Wisoky-Harris');
insert into Client_Data (client_id, company_name) values (400769, 'Krajcik, Price and Schroeder');
insert into Client_Data (client_id, company_name) values (400770, 'Oberbrunner, Stiedemann and Mante');
insert into Client_Data (client_id, company_name) values (400771, 'Lockman Group');
insert into Client_Data (client_id, company_name) values (400772, 'Anderson, Gerlach and Schamberger');
insert into Client_Data (client_id, company_name) values (400773, 'Smitham-Koch');
insert into Client_Data (client_id, company_name) values (400774, 'Roberts and Sons');
insert into Client_Data (client_id, company_name) values (400775, 'Beatty, Waelchi and Wunsch');
insert into Client_Data (client_id, company_name) values (400776, 'Gaylord, Hoppe and Mante');
insert into Client_Data (client_id, company_name) values (400777, 'Swift, Hilll and Padberg');
insert into Client_Data (client_id, company_name) values (400778, 'Haag, Marquardt and Erdman');
insert into Client_Data (client_id, company_name) values (400779, 'Stark-Wintheiser');
insert into Client_Data (client_id, company_name) values (400780, 'O''Connell, Monahan and Krajcik');
insert into Client_Data (client_id, company_name) values (400781, 'Ortiz, Tillman and Bosco');
insert into Client_Data (client_id, company_name) values (400782, 'Schuppe-Rodriguez');
insert into Client_Data (client_id, company_name) values (400783, 'Conroy-Feil');
insert into Client_Data (client_id, company_name) values (400784, 'Davis Inc');
insert into Client_Data (client_id, company_name) values (400785, 'Pollich-Dietrich');
insert into Client_Data (client_id, company_name) values (400786, 'Eichmann LLC');
insert into Client_Data (client_id, company_name) values (400787, 'Welch-Stark');
insert into Client_Data (client_id, company_name) values (400788, 'Marquardt, Kunze and Kuvalis');
insert into Client_Data (client_id, company_name) values (400789, 'Brekke LLC');
insert into Client_Data (client_id, company_name) values (400790, 'Douglas-Feeney');
insert into Client_Data (client_id, company_name) values (400791, 'Beer-Cole');
insert into Client_Data (client_id, company_name) values (400792, 'Dooley Inc');
insert into Client_Data (client_id, company_name) values (400793, 'Blanda Group');
insert into Client_Data (client_id, company_name) values (400794, 'Will-Halvorson');
insert into Client_Data (client_id, company_name) values (400795, 'Mohr-Mann');
insert into Client_Data (client_id, company_name) values (400796, 'Prosacco, Cronin and Stamm');
insert into Client_Data (client_id, company_name) values (400797, 'Gottlieb-Jacobs');
insert into Client_Data (client_id, company_name) values (400798, 'Quitzon, Russel and Reichel');
insert into Client_Data (client_id, company_name) values (400799, 'Daugherty Inc');
insert into Client_Data (client_id, company_name) values (400800, 'Cartwright Inc');
insert into Client_Data (client_id, company_name) values (400801, 'Douglas-Herman');
insert into Client_Data (client_id, company_name) values (400802, 'Jacobson, Sanford and Greenholt');
insert into Client_Data (client_id, company_name) values (400803, 'Thiel-Hintz');
insert into Client_Data (client_id, company_name) values (400804, 'Kutch, Wisoky and Block');
insert into Client_Data (client_id, company_name) values (400805, 'Heaney, Waters and Lynch');
insert into Client_Data (client_id, company_name) values (400806, 'Rau-Weissnat');
insert into Client_Data (client_id, company_name) values (400807, 'Abernathy-Parisian');
insert into Client_Data (client_id, company_name) values (400808, 'Lowe, Bins and Stehr');
insert into Client_Data (client_id, company_name) values (400809, 'Streich, Johns and Abernathy');
insert into Client_Data (client_id, company_name) values (400810, 'Grant-Hagenes');
insert into Client_Data (client_id, company_name) values (400811, 'Collier Inc');
insert into Client_Data (client_id, company_name) values (400812, 'Bartell LLC');
insert into Client_Data (client_id, company_name) values (400813, 'Windler, Schmeler and Corkery');
insert into Client_Data (client_id, company_name) values (400814, 'Paucek LLC');
insert into Client_Data (client_id, company_name) values (400815, 'Cronin-Okuneva');
insert into Client_Data (client_id, company_name) values (400816, 'Terry-Raynor');
insert into Client_Data (client_id, company_name) values (400817, 'Wuckert, Hintz and Blick');
insert into Client_Data (client_id, company_name) values (400818, 'Reichel-Fahey');
insert into Client_Data (client_id, company_name) values (400819, 'Cremin, Senger and Heathcote');
insert into Client_Data (client_id, company_name) values (400820, 'O''Keefe-Considine');
insert into Client_Data (client_id, company_name) values (400821, 'Ondricka-Borer');
insert into Client_Data (client_id, company_name) values (400822, 'Lubowitz-Brown');
insert into Client_Data (client_id, company_name) values (400823, 'Hansen-Jerde');
insert into Client_Data (client_id, company_name) values (400824, 'Nolan-Lang');
insert into Client_Data (client_id, company_name) values (400825, 'Weimann and Sons');
insert into Client_Data (client_id, company_name) values (400826, 'Jaskolski, Koelpin and Bins');
insert into Client_Data (client_id, company_name) values (400827, 'O''Kon, Durgan and Veum');
insert into Client_Data (client_id, company_name) values (400828, 'Goyette, White and Keeling');
insert into Client_Data (client_id, company_name) values (400829, 'Wisoky, Cummings and Schmidt');
insert into Client_Data (client_id, company_name) values (400830, 'Olson, Wisoky and Kautzer');
insert into Client_Data (client_id, company_name) values (400831, 'Bahringer and Sons');
insert into Client_Data (client_id, company_name) values (400832, 'Ferry, Howell and Wilderman');
insert into Client_Data (client_id, company_name) values (400833, 'Daniel-Mohr');
insert into Client_Data (client_id, company_name) values (400834, 'Huel-West');
insert into Client_Data (client_id, company_name) values (400835, 'Padberg-Spinka');
insert into Client_Data (client_id, company_name) values (400836, 'Goyette, Blanda and Zemlak');
insert into Client_Data (client_id, company_name) values (400837, 'Treutel Inc');
insert into Client_Data (client_id, company_name) values (400838, 'Kshlerin LLC');
insert into Client_Data (client_id, company_name) values (400839, 'Heidenreich, Green and Schoen');
insert into Client_Data (client_id, company_name) values (400840, 'Graham-Mohr');
insert into Client_Data (client_id, company_name) values (400841, 'Graham, Sawayn and Bednar');
insert into Client_Data (client_id, company_name) values (400842, 'Smith-Jones');
insert into Client_Data (client_id, company_name) values (400843, 'Bosco-Parisian');
insert into Client_Data (client_id, company_name) values (400844, 'Jaskolski-Breitenberg');
insert into Client_Data (client_id, company_name) values (400845, 'Ankunding, Predovic and Hagenes');
insert into Client_Data (client_id, company_name) values (400846, 'Little, Welch and Reinger');
insert into Client_Data (client_id, company_name) values (400847, 'Berge Inc');
insert into Client_Data (client_id, company_name) values (400848, 'Pfeffer, Sanford and Fisher');
insert into Client_Data (client_id, company_name) values (400849, 'Kozey-Abbott');
insert into Client_Data (client_id, company_name) values (400850, 'Windler-Ullrich');
insert into Client_Data (client_id, company_name) values (400851, 'Hyatt, Bode and Hackett');
insert into Client_Data (client_id, company_name) values (400852, 'Oberbrunner, Nader and Murazik');
insert into Client_Data (client_id, company_name) values (400853, 'Gleichner, Kilback and Tromp');
insert into Client_Data (client_id, company_name) values (400854, 'Stoltenberg-Kertzmann');
insert into Client_Data (client_id, company_name) values (400855, 'Swaniawski-Homenick');
insert into Client_Data (client_id, company_name) values (400856, 'Gislason, Schneider and Glover');
insert into Client_Data (client_id, company_name) values (400857, 'Kub-Hodkiewicz');
insert into Client_Data (client_id, company_name) values (400858, 'Swaniawski, Nader and MacGyver');
insert into Client_Data (client_id, company_name) values (400859, 'Mann, Marks and Runolfsdottir');
insert into Client_Data (client_id, company_name) values (400860, 'Lang Inc');
insert into Client_Data (client_id, company_name) values (400861, 'Emard-Pouros');
insert into Client_Data (client_id, company_name) values (400862, 'Herman, Abernathy and Ward');
insert into Client_Data (client_id, company_name) values (400863, 'Hessel, Braun and Waelchi');
insert into Client_Data (client_id, company_name) values (400864, 'Rempel and Sons');
insert into Client_Data (client_id, company_name) values (400865, 'Jenkins-Lubowitz');
insert into Client_Data (client_id, company_name) values (400866, 'Schuster, Langworth and Jaskolski');
insert into Client_Data (client_id, company_name) values (400867, 'Jacobi-Dach');
insert into Client_Data (client_id, company_name) values (400868, 'Kerluke and Sons');
insert into Client_Data (client_id, company_name) values (400869, 'Emard LLC');
insert into Client_Data (client_id, company_name) values (400870, 'Davis-Howe');
insert into Client_Data (client_id, company_name) values (400871, 'Haley, Wiza and Lynch');
insert into Client_Data (client_id, company_name) values (400872, 'Feeney-Ernser');
insert into Client_Data (client_id, company_name) values (400873, 'Von, Feest and Cremin');
insert into Client_Data (client_id, company_name) values (400874, 'Kozey Inc');
insert into Client_Data (client_id, company_name) values (400875, 'Armstrong, Turcotte and Pfannerstill');
insert into Client_Data (client_id, company_name) values (400876, 'Kohler, Abshire and Stroman');
insert into Client_Data (client_id, company_name) values (400877, 'Steuber, Pollich and Bergnaum');
insert into Client_Data (client_id, company_name) values (400878, 'Torphy LLC');
insert into Client_Data (client_id, company_name) values (400879, 'Ward, Harris and Herman');
insert into Client_Data (client_id, company_name) values (400880, 'Hessel, Goodwin and Lesch');
insert into Client_Data (client_id, company_name) values (400881, 'Romaguera and Sons');
insert into Client_Data (client_id, company_name) values (400882, 'Leuschke, Braun and Rippin');
insert into Client_Data (client_id, company_name) values (400883, 'Klein, Kunde and Cummerata');
insert into Client_Data (client_id, company_name) values (400884, 'Kilback, Wilkinson and Klocko');
insert into Client_Data (client_id, company_name) values (400885, 'Botsford-Parisian');
insert into Client_Data (client_id, company_name) values (400886, 'Reichel-Douglas');
insert into Client_Data (client_id, company_name) values (400887, 'Jacobson Inc');
insert into Client_Data (client_id, company_name) values (400888, 'Rowe, Hoeger and O''Conner');
insert into Client_Data (client_id, company_name) values (400889, 'Spinka, Howell and Torphy');
insert into Client_Data (client_id, company_name) values (400890, 'Smith-Fay');
insert into Client_Data (client_id, company_name) values (400891, 'Durgan-Lockman');
insert into Client_Data (client_id, company_name) values (400892, 'Denesik-Kuhlman');
insert into Client_Data (client_id, company_name) values (400893, 'Bode, Bergstrom and Hamill');
insert into Client_Data (client_id, company_name) values (400894, 'Upton LLC');
insert into Client_Data (client_id, company_name) values (400895, 'Hodkiewicz Inc');
insert into Client_Data (client_id, company_name) values (400896, 'Rosenbaum-Tremblay');
insert into Client_Data (client_id, company_name) values (400897, 'Blick and Sons');
insert into Client_Data (client_id, company_name) values (400898, 'Smitham, O''Reilly and King');
insert into Client_Data (client_id, company_name) values (400899, 'Ankunding, Wolff and Kunze');
insert into Client_Data (client_id, company_name) values (400900, 'Leannon and Sons');
insert into Client_Data (client_id, company_name) values (400901, 'Rippin LLC');
insert into Client_Data (client_id, company_name) values (400902, 'Feest Group');
insert into Client_Data (client_id, company_name) values (400903, 'Streich and Sons');
insert into Client_Data (client_id, company_name) values (400904, 'Flatley LLC');
insert into Client_Data (client_id, company_name) values (400905, 'Kozey and Sons');
insert into Client_Data (client_id, company_name) values (400906, 'Jacobi LLC');
insert into Client_Data (client_id, company_name) values (400907, 'Stehr LLC');
insert into Client_Data (client_id, company_name) values (400908, 'Legros-Homenick');
insert into Client_Data (client_id, company_name) values (400909, 'Herzog, O''Kon and Hettinger');
insert into Client_Data (client_id, company_name) values (400910, 'O''Hara and Sons');
insert into Client_Data (client_id, company_name) values (400911, 'Klein, Collier and Haag');
insert into Client_Data (client_id, company_name) values (400912, 'Watsica-Heathcote');
insert into Client_Data (client_id, company_name) values (400913, 'Schumm-Boyer');
insert into Client_Data (client_id, company_name) values (400914, 'Fay, Kuhic and Harvey');
insert into Client_Data (client_id, company_name) values (400915, 'Ryan, Marquardt and Thompson');
insert into Client_Data (client_id, company_name) values (400916, 'Boyer-Pfeffer');
insert into Client_Data (client_id, company_name) values (400917, 'Torp-Romaguera');
insert into Client_Data (client_id, company_name) values (400918, 'Orn LLC');
insert into Client_Data (client_id, company_name) values (400919, 'Schultz and Sons');
insert into Client_Data (client_id, company_name) values (400920, 'Simonis LLC');
insert into Client_Data (client_id, company_name) values (400921, 'Rolfson-Wintheiser');
insert into Client_Data (client_id, company_name) values (400922, 'Schmeler, Bruen and Wunsch');
insert into Client_Data (client_id, company_name) values (400923, 'Weimann Inc');
insert into Client_Data (client_id, company_name) values (400924, 'Carter-Bechtelar');
insert into Client_Data (client_id, company_name) values (400925, 'Schultz-Pouros');
insert into Client_Data (client_id, company_name) values (400926, 'Brown-Bauch');
insert into Client_Data (client_id, company_name) values (400927, 'Lockman-Stark');
insert into Client_Data (client_id, company_name) values (400928, 'Volkman-Oberbrunner');
insert into Client_Data (client_id, company_name) values (400929, 'Lowe, Kemmer and Cruickshank');
insert into Client_Data (client_id, company_name) values (400930, 'Auer, O''Kon and Hamill');
insert into Client_Data (client_id, company_name) values (400931, 'Beahan-Waelchi');
insert into Client_Data (client_id, company_name) values (400932, 'Sauer and Sons');
insert into Client_Data (client_id, company_name) values (400933, 'Buckridge, Moore and Yost');
insert into Client_Data (client_id, company_name) values (400934, 'Bartell and Sons');
insert into Client_Data (client_id, company_name) values (400935, 'Pagac, Farrell and Mante');
insert into Client_Data (client_id, company_name) values (400936, 'Harber-Boyer');
insert into Client_Data (client_id, company_name) values (400937, 'Skiles Group');
insert into Client_Data (client_id, company_name) values (400938, 'Vandervort-Marquardt');
insert into Client_Data (client_id, company_name) values (400939, 'Lehner Group');
insert into Client_Data (client_id, company_name) values (400940, 'Bartoletti-Schaden');
insert into Client_Data (client_id, company_name) values (400941, 'Durgan Group');
insert into Client_Data (client_id, company_name) values (400942, 'Grimes, Kemmer and Walsh');
insert into Client_Data (client_id, company_name) values (400943, 'Buckridge-Cummings');
insert into Client_Data (client_id, company_name) values (400944, 'Graham-Willms');
insert into Client_Data (client_id, company_name) values (400945, 'Jenkins, Pouros and Effertz');
insert into Client_Data (client_id, company_name) values (400946, 'Keebler-Schroeder');
insert into Client_Data (client_id, company_name) values (400947, 'Kessler Group');
insert into Client_Data (client_id, company_name) values (400948, 'Effertz LLC');
insert into Client_Data (client_id, company_name) values (400949, 'Bode-Russel');
insert into Client_Data (client_id, company_name) values (400950, 'Jacobi-Marks');
insert into Client_Data (client_id, company_name) values (400951, 'Heathcote Group');
insert into Client_Data (client_id, company_name) values (400952, 'Flatley LLC');
insert into Client_Data (client_id, company_name) values (400953, 'Wisozk-Olson');
insert into Client_Data (client_id, company_name) values (400954, 'Wuckert-Kulas');
insert into Client_Data (client_id, company_name) values (400955, 'Windler and Sons');
insert into Client_Data (client_id, company_name) values (400956, 'Waelchi, Wisoky and Boyer');
insert into Client_Data (client_id, company_name) values (400957, 'Stanton-Senger');
insert into Client_Data (client_id, company_name) values (400958, 'Friesen, Greenfelder and Gibson');
insert into Client_Data (client_id, company_name) values (400959, 'Goyette-Barrows');
insert into Client_Data (client_id, company_name) values (400960, 'Littel-Labadie');
insert into Client_Data (client_id, company_name) values (400961, 'Farrell, McClure and Weimann');
insert into Client_Data (client_id, company_name) values (400962, 'Murphy, Bosco and West');
insert into Client_Data (client_id, company_name) values (400963, 'Ward-O''Conner');
insert into Client_Data (client_id, company_name) values (400964, 'Reichel-West');
insert into Client_Data (client_id, company_name) values (400965, 'Rau Inc');
insert into Client_Data (client_id, company_name) values (400966, 'Jacobson-Barrows');
insert into Client_Data (client_id, company_name) values (400967, 'Schmidt and Sons');
insert into Client_Data (client_id, company_name) values (400968, 'Gaylord-Kovacek');
insert into Client_Data (client_id, company_name) values (400969, 'Murphy Group');
insert into Client_Data (client_id, company_name) values (400970, 'Dooley, Wyman and Schneider');
insert into Client_Data (client_id, company_name) values (400971, 'Durgan Inc');
insert into Client_Data (client_id, company_name) values (400972, 'Johns-Bayer');
insert into Client_Data (client_id, company_name) values (400973, 'Schaefer-Auer');
insert into Client_Data (client_id, company_name) values (400974, 'Parisian and Sons');
insert into Client_Data (client_id, company_name) values (400975, 'Botsford, Emmerich and Maggio');
insert into Client_Data (client_id, company_name) values (400976, 'Boehm-Schamberger');
insert into Client_Data (client_id, company_name) values (400977, 'Oberbrunner, Leannon and Osinski');
insert into Client_Data (client_id, company_name) values (400978, 'Kemmer, Cole and Goodwin');
insert into Client_Data (client_id, company_name) values (400979, 'Bartoletti, Bartoletti and Mills');
insert into Client_Data (client_id, company_name) values (400980, 'Stark LLC');
insert into Client_Data (client_id, company_name) values (400981, 'Muller-Collins');
insert into Client_Data (client_id, company_name) values (400982, 'Stehr-Pollich');
insert into Client_Data (client_id, company_name) values (400983, 'Bernhard-Tremblay');
insert into Client_Data (client_id, company_name) values (400984, 'Harris, Sporer and Reinger');
insert into Client_Data (client_id, company_name) values (400985, 'West-Turner');
insert into Client_Data (client_id, company_name) values (400986, 'Roberts-Hoeger');
insert into Client_Data (client_id, company_name) values (400987, 'Effertz, Flatley and Toy');
insert into Client_Data (client_id, company_name) values (400988, 'Shanahan LLC');
insert into Client_Data (client_id, company_name) values (400989, 'Gaylord-Hansen');
insert into Client_Data (client_id, company_name) values (400990, 'Cremin Inc');
insert into Client_Data (client_id, company_name) values (400991, 'Anderson-Lemke');
insert into Client_Data (client_id, company_name) values (400992, 'Heller-Batz');
insert into Client_Data (client_id, company_name) values (400993, 'Weimann LLC');
insert into Client_Data (client_id, company_name) values (400994, 'Dicki, Kohler and Schaden');
insert into Client_Data (client_id, company_name) values (400995, 'O''Keefe, Huel and Ullrich');
insert into Client_Data (client_id, company_name) values (400996, 'Zboncak LLC');
insert into Client_Data (client_id, company_name) values (400997, 'Herman-Rau');
insert into Client_Data (client_id, company_name) values (400998, 'Schulist LLC');
insert into Client_Data (client_id, company_name) values (400999, 'Bernier LLC');
